Repository SoftEng701-Group5/assignment1, pull requests merged in 2021-03, with the labels that each got.

#6 Uploaded Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#20 Sync main branch commits
  package-lock.json
  src/App.css
  src/App.test.js
  src/index.css
Labels: bug

#25 #22 Add global styling, home page, and global button
  src/App.js
  src/assets/icons/RightChevron.jsx
  src/components/global/Button.jsx
  src/pages/homeView.js
  src/stylesheets/app.scss
  src/stylesheets/components/global/button.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#29 Add global styling, home page, and global button (#25)
  src/App.js
  src/assets/icons/RightChevron.jsx
  src/components/global/Button.jsx
  src/pages/homeView.js
  src/stylesheets/app.scss
  src/stylesheets/components/global/button.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#21 Update README.md
  README.md
Labels: documentation

#38 Feature navbar
  src/App.js
  src/assets/icons/BoardIcon.jsx
  src/assets/icons/DashboardIcon.jsx
  src/assets/icons/ExpandIcon.jsx
  src/assets/icons/HomeIcon.jsx
  src/assets/icons/LogoutIcon.jsx
  src/assets/icons/MinimizeIcon.jsx
  src/assets/icons/PlusIcon.jsx
  src/assets/icons/SettingsIcon.jsx
  src/assets/images/default-avatar.png
  src/components/Navbar.jsx
  src/stylesheets/app.scss
  src/stylesheets/components/navbar.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#45 Fix main content size
  src/stylesheets/app.scss
Labels: bug

#43 Bugfix nav account icons
  src/stylesheets/components/navbar.scss
Labels: bug

#42 Global task button component
  package-lock.json
  src/assets/icons/BoardIcon.jsx
  src/assets/icons/RightChevron.jsx
  src/components/global/Task/Subtask.jsx
  src/components/global/Task/Task.jsx
  src/stylesheets/assets/right-chevron.scss
  src/stylesheets/components/global/task/subtask.scss
  src/stylesheets/components/global/task/task.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#40 firebase authorization methods added
  package-lock.json
  src/services/authService.js
  src/services/firebase.js
  src/services/providers/authProvider.js
Labels: enhancement

#67 Set Up ESLint and Fix Linting Problems
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/assets/icons/ExpandIcon.jsx
  src/assets/icons/MinimizeIcon.jsx
  src/assets/icons/PlusIcon.jsx
  src/assets/icons/RightChevron.jsx
  src/assets/icons/SettingsIcon.jsx
  src/assets/images/BoardImage.jsx
  src/assets/images/HomepageImage.jsx
  src/assets/images/LoginImage.jsx
  src/assets/images/SignupImage.jsx
  src/components/Navbar.jsx
  src/components/global/Button.jsx
  src/components/global/IconButton.jsx
  src/components/global/Task/Subtask.jsx
  src/components/global/Task/Task.jsx
  src/components/global/TextInput.jsx
  src/components/global/componentFunctions.js
  src/components/global/componentFunctions.jsx
  src/pages/homeView.js
  src/pages/loginView.js
  src/pages/pageNotFoundView.js
  src/tests/App.test.js
Labels: initial setup

#70 Removing Unnecessary Linting Rules
  .eslintrc.js
Labels: enhancement

#78 made the sign-up method add first and last name to user
  src/services/authService.js
Labels: enhancement

#83 Feature firebase crud
  package-lock.json
  package.json
  src/components/PrivateRoute.js
  src/services/authService.js
  src/services/databaseService.js
  src/services/firebase.js
  src/services/providers/authProvider.js
Labels: enhancement

#72 Feature timer config
  src/components/current-task/CurrentTask.jsx
  src/components/current-task/TimerConfig.jsx
  src/components/global/TextInput.jsx
  src/stylesheets/components/current-task/timerConfig.scss
  src/stylesheets/components/global/textInput.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#108 Set Up Continuous Integration Through Github Actions
  .github/workflows/build_and_deploy.yml
  package-lock.json
  package.json
  src/App.js
  src/pages/loginView.js
  src/pages/signUpView.js
  src/stylesheets/index.scss
Labels: initial setup

#82 Added new task component
  public/index.html
  src/assets/icons/CrossIcon.jsx
  src/components/NewTask.jsx
  src/components/global/AddButton.jsx
  src/components/global/Modal.jsx
  src/components/global/TextInput.jsx
  src/components/global/componentFunctions.jsx
  src/stylesheets/components/global/addButton.scss
  src/stylesheets/components/global/modal.scss
  src/stylesheets/components/newTaskModalContent.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#109 Add Linting and Testing Github Action Workflow for Continuous Integration
  .github/disabled-workflows/tests.yml
  .github/workflows/eslint_and_prettier.yml
  README.md
Labels: enhancement, initial setup

#91 Bugfix scale down navbar icons
  src/assets/icons/BoardIcon.jsx
  src/assets/icons/DashboardIcon.jsx
  src/assets/icons/HomeIcon.jsx
  src/pages/homeView.js
  src/stylesheets/components/global/button.scss
  src/stylesheets/components/global/iconButton.scss
  src/stylesheets/components/navbar.scss
  src/stylesheets/variables.scss
Labels: bug

#116 Feature homepage
  src/assets/images/HomepageImage.jsx
  src/components/DateTime.jsx
  src/pages/homeView.js
  src/stylesheets/home.scss
  src/stylesheets/index.scss
Labels: enhancement

#112 Add persistence to new task modal
  package-lock.json
  package.json
  src/components/NewTask.jsx
  src/stylesheets/components/newTaskModalContent.scss
  src/stylesheets/variables.scss
Labels: enhancement

#118 Feature new task
  package-lock.json
  package.json
  src/assets/icons/CrossIcon.jsx
  src/components/NewTask.jsx
  src/components/global/AddButton.jsx
  src/components/global/Modal.jsx
  src/components/global/componentFunctions.jsx
  src/stylesheets/components/global/addButton.scss
  src/stylesheets/components/global/modal.scss
  src/stylesheets/components/newTaskModalContent.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: enhancement

#106 Bugfix reset inputs on failed signup/login
  src/pages/loginView.js
  src/pages/signUpView.js
Labels: bug

#122 Update main
  package-lock.json
  package.json
  src/assets/icons/CrossIcon.jsx
  src/components/NewTask.jsx
  src/components/global/AddButton.jsx
  src/components/global/Modal.jsx
  src/components/global/componentFunctions.jsx
  src/pages/loginView.js
  src/pages/signUpView.js
  src/stylesheets/components/global/addButton.scss
  src/stylesheets/components/global/modal.scss
  src/stylesheets/components/newTaskModalContent.scss
  src/stylesheets/index.scss
  src/stylesheets/variables.scss
Labels: bug, enhancement

#137 Timer config inputs update on change
  src/components/current-task/TimerConfig.jsx
Labels: bug

#141 Feature firebase on auth changed fix
  src/services/providers/authProvider.js
Labels: bug

#148 Feature task list
  package-lock.json
  src/components/NewTask.jsx
  src/components/global/TaskList.jsx
  src/stylesheets/components/global/taskList.scss
Labels: enhancement

#133 Basic Tests
  .gitignore
  src/components/Navbar.jsx
  src/tests/App.test.js
  src/tests/components/Button.test.jsx
  src/tests/components/Task.test.jsx
Labels: initial setup

#154 Feature welcome dashboard
  src/App.js
  src/components/Navbar.jsx
  src/components/NewTask.jsx
  src/components/current-task/CurrentTask.jsx
  src/components/current-task/CurrentTaskTimer.jsx
  src/components/current-task/TimerConfig.jsx
  src/components/global/Button.jsx
  src/components/global/IconButton.jsx
  src/components/global/Task/Task.jsx
  src/components/global/TaskList.jsx
  src/components/timer-modal/TimerContextProvider.js
  src/components/timer-modal/TimerData.js
  src/components/timer-modal/TimerModal.jsx
  src/components/timer-modal/TimerSection.jsx
  src/pages/dashboardView.js
  src/pages/homeView.js
  src/pages/loginView.js
  src/stylesheets/app.scss
  src/stylesheets/components/current-task/currentTask.scss
  src/stylesheets/components/current-task/currentTaskTimer.scss
  src/stylesheets/components/global/addButton.scss
  src/stylesheets/components/global/button.scss
  src/stylesheets/components/global/task/task.scss
  src/stylesheets/components/global/taskList.scss
  src/stylesheets/components/timer-modal/timerModal.scss
  src/stylesheets/dashboard.scss
  src/stylesheets/index.scss
  src/stylesheets/mixins.scss
  src/stylesheets/variables.scss
Labels: enhancement

#163 Update project name and add icon
  public/favicon.ico
  public/index.html
Labels: enhancement

#165 Setup CI Testing Workflow
  .github/workflows/tests.yml
  README.md
  src/components/Navbar.jsx
Labels: enhancement, initial setup

#169 Add task list to home page and fix list css
  src/pages/homeView.js
  src/stylesheets/components/global/taskList.scss
  src/stylesheets/home.scss
Labels: enhancement

#181 Completed Code of Conduct, ready for merging with main
  CODE_OF_CONDUCT.md
Labels: documentation

#177 Feature task board
  package-lock.json
  package.json
  src/App.js
  src/assets/TaskBoardSampleData.js
  src/components/global/Task/BoardTask.jsx
  src/components/global/Task/Task.jsx
  src/components/task-board/TaskBoardColumn.jsx
  src/pages/boardView.js
  src/stylesheets/boardView.scss
  src/stylesheets/components/navbar.scss
  src/stylesheets/components/task-board/taskBoardColumn.scss
  src/stylesheets/index.scss
Labels: TaskBoard, enhancement

#218 Adding Github Pull Request and Issue Templates
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, enhancement

#228 Comments for files associated with the Dashboard
  src/components/current-task/CurrentTask.jsx
  src/components/current-task/CurrentTaskNotes.jsx
  src/components/current-task/CurrentTaskTimer.jsx
  src/components/current-task/TimerConfig.jsx
  src/components/global/TaskList.jsx
  src/pages/dashboardView.js
Labels: documentation

#219 Comments for new task and modal component
  src/components/NewTask.jsx
  src/components/global/Modal.jsx
Labels: documentation

#229 End to End Testing
  .eslintrc.js
  .github/workflows/end_to_end_tests.yml
  .gitignore
  README.md
  cypress.json
  cypress/integration/Tests/App.E2ETests.js
  package-lock.json
  package.json
  src/components/Navbar.jsx
  src/pages/signUpView.js
  src/tests/App.test.js
  src/tests/components/DateTime.test.jsx
Labels: testing

#230 Corrected location of the Pull Request Template
  .github/pull_request_template.md
Labels: bug

#233 Changed End-to-End tests to run on Pull Requests
  .github/workflows/end_to_end_tests.yml
Labels: bug, testing

#234 Updated README.md
  CONTRIBUTING.md
  README.md
Labels: documentation
